version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    ports:
      - "9090:9090"

  # db is is db folder
  db:
    build: db/.
    restart: always
    environment:
      # Corrected: Should be MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: example
      # Corrected: Should be MYSQL_DATABASE
      MYSQL_DATABASE: employees
      # *** THIS IS THE CRITICAL TYPO FIX ***
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33060:3306"


  web:
    build: ./web
    container_name: semethods-web
    ports:
      - "80:80"
    depends_on:
      - app