language: java

sudo: false

addons:
  hosts:
    - db

services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk18
      script:
        - mvn test -Dtest=com.napier.sem.Testing

    - stage: integration tests
      jdk: oraclejdk18
      script:
        - mvn test -Dtest=com.napier.devops.AppIntegrationTest

    - stage: GitHub Release
      install: skip
      jdk: oraclejdk18
      script:
        - echo "Deploying to GitHub Releases"
        - mvn package -DskipTests=true -Dmaven.javadoc.skip=true

      before_deploy:
        - git config --local user.name "LamBirD"
        - git config --local user.email "thutaminlu30@gmail.com"
        - export TRAVIS_TAG="${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}"
        - git tag "$TRAVIS_TAG"

      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "$TRAVIS_BUILD_DIR/target/devops.jar"
        skip_cleanup: true

stages:
  - unit tests
  - integration tests
  - name: GitHub Release
    if: branch == hotfix

after_success:
  - bash <(curl -s https://codecov.io/bash)
