name: Java CI/CD

on:
  push:
    branches:
      - hotfix
  workflow_dispatch:

jobs:
  setup-database:
    name: Setup MySQL Docker
    runs-on: ubuntu-latest
    outputs:
      db-port: ${{ steps.db.outputs.db-port }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t database db/.

      - name: Run MySQL container
        id: db
        run: |
          docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
          echo "db-port=33060" >> $GITHUB_OUTPUT

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup-database
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Maven install
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Clean project
        run: mvn clean

      - name: Run Unit Tests
        run: mvn test -Dtest=com.napier.sem.Testing

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: setup-database
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Maven install
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Run Integration Tests
        run: mvn test -Dtest=com.napier.devops.AppIntegrationTest

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Maven package
        run: mvn package -DskipTests=true -Dmaven.javadoc.skip=true

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_number }}-${{ github.sha }}
          release_name: Release ${{ github.run_number }}-${{ github.sha }}
          draft: false
          prerelease: false
          body: Automated release from workflow
          token: ${{ secrets.GITHUB_OAUTH_TOKEN }}

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/devops.jar
          asset_name: devops.jar
          asset_content_type: application/java-archive